const students = {
  "Blake A": ["https://replit.com/@whassuppal/CYOA-FINAL"],
  "Ty N": ["https://2vs5qo.csb.app/"],
  "Atticus R": ["https://final-project-cs.mckellhardman.repl.co"],
  "Abby H": ["https://replit.com/@Abbers/CYOA-p5#script.js"],
  "Ayden W": ["https://Actual-Final-CS-Project-Attemt-4.awoof07.repl.co"],
  "Devin H": ["https://DinosaurDE.ethanapsley1.repl.co"],
  "Ethan A": ["https://DinosaurDE.ethanapsley1.repl.co"],
  "Ben B": ["https://replit.com/@BenBoucher/Circular-Jungle"],
  "Shantel G": ["https://Jarorld-the-Block-Friend.hamyyystar.repl.co"],
  "McKell H": ["https://final-project-cs.mckellhardman.repl.co"],
  "Alan M": ["https://replit.com/@Jibusentanna/DinoGameP5Starter-3"],
  "Gibson T": ["https://replit.com/@Jibusentanna/DinoGameP5Starter-3"],
  "Logan H":["https://bean-jumper.dunkteam42.repl.co/"],
  "Neeve R": ["https://platform-jumping.zebra06.repl.co/"],
  "Isaac H": ["https://Tank-game2.tristan646.repl.co"],
  "Jaxon D": ["https://Final-project-JETPACK-BOIRIDE.jaquaviondamark.repl.co"],
  "Owen C":["https://quandale-dingle-escape.orcowles.repl.co/"],
  "Xane C": ["https://replit.com/@mc0398971/Game-JIC"],
  "Lucy G": ["https://1919-Game.lucygolden.repl.co"],
  "Eleanor A" : ["https://Cool-Thing.coolcello.repl.co"],
  "Amy R": ["https://final-project.amyyr21.repl.co/"],
  "Jared B": ["https://replit.com/@JABJAB1/CS-final-project-Hunt-the-Wumpus#script.js",
"https://replit.com/@JABJAB1/DandD-fun#index.html", "https://replit.com/@JABJAB1/multi-page-project#index.html"],
  "Abbey B": ["https://replit.com/@Abbey0Cadabby/THE-RUNAWAYgreater#index.html"],
  "Jonas A": ["https://quandale-dingle-escape.orcowles.repl.co/"],
  "Miekah B": ["https://cyoa-p5.bug5608.repl.co/"],
  "Yader B": ["https://replit.com/@omarrangel2/CYOA-p5-1#script.js"],
  "Ty D": ["https://final-project-jetpack-boiride.jaquaviondamark.repl.co/"],
  "Eliot F": ["https://final-project.farmeeli.repl.co/"],
  "Gavin F": ["https://mike-wazowski-story.39nelg.repl.co/"],
  "Veronica G": ["https://replit.com/@VeronicaGao/Final-Project-CYOA?v=1"],
  "Raymon H": ["https://pokeapi-1.leonel6556.repl.co/"],
  "Kate K": ["https://replit.com/@KateKeeley/CYOA-p5#script.js"],
  "Brianna L": ["https://dinogamep5starter.camiller2021.repl.co/"],
  "Marc S": ["https://fighter.lilpenguincode.repl.co/"],
  "James M": ["https://fighter.lilpenguincode.repl.co/"],
  "Leonel M": ["https://pokeapi-1.leonel6556.repl.co/"],
  "EJ N": ["https://pokemon-adventure.nielson17.repl.co/"],
  "Wes P": ["https://replit.com/@joshyboi16/daddy-wes-is-super-hot"],
  "Camille R": ["https://replit.com/@CamilleR2021/DinoGameP5Starter#globals.js"],
  "Omar R": ["https://replit.com/@omarrangel2/CYOA-p5-1#script.js"],
  "Glen S": ["https://mike-wazowski-story.39nelg.repl.co/"],
  "Josh S": ["https://daddy-wes-is-super-hot.joshyboi16.repl.co/"],
  "Lydia S": ["https://rectangle-road-game.85979.repl.co/"],
  "Noah S": ["https://bean-jumper.dunkteam42.repl.co/"],
  "Mariah V": ["https://replit.com/@mariah-valen01/DinoGameP5Starter"],
  "Samantha S": ["https://replit.com/@mariah-valen01/DinoGameP5Starter"],
  "Maria W": ["https://cyoa-p5-1.crimsoncrow7900.repl.co/"],
  "Stephanie W": ["https://replit.com/@IceFairyPearl2/AfterLife-Seers-Adventure-Challenge"],
};

const studentsSorted = Object.keys(students)
  .sort()
  .reduce((obj, key) => {
    obj[key] = students[key];
    return obj;
  }, {});

export default studentsSorted;
